### ISSUE TITLE
Boxes adds './bin/ to your path

### ISSUE THREAD

**Issue by norm-modustri** [modustri/boxen#15]
Boxes appears to add any `bin` dir to your path. Whenever your in a dir that has it's own `bin` directory, bash will look in that dir first before trying other `bin` directories. This can cause commands to not be found if you have a `bin` dir referenced later in your paths:  For example, my path is: 

```
/opt/boxen/pyenv/shims:/opt/boxen/rbenv/shims:/opt/boxen/heroku/bin:bin:/opt/boxen/rbenv/shims:/opt/boxen/rbenv/bin:/opt/boxen/ruby-build/bin:/opt/boxen/pyenv/shims:/opt/boxen/pyenv/bin:/opt/boxen/phantomenv/shims:/opt/boxen/phantomenv/bin:/opt/boxen/nodenv/shims:/opt/boxen/nodenv/bin:/opt/boxen/node-build/bin:/opt/boxen/homebrew/bin:/opt/boxen/homebrew/sbin:/opt/boxen/bin:/Users/normbarnard/bin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
```
I have a `/Users/normbarnard/bin` dir where i keep some local command and shell script. If i'm in a directory that contains a local `bin` folder, i will get the following error: 

```
[normbarnard@Norms-MacBook-Pro ~/Modustri/api] dev-servers.sh start
-bash: bin/dev-servers.sh: No such file or directory
```
if I however, `cd` to a different folder it seems to work.

This is probably caused by the script named `90_relative_bin_on_path.sh` that lives in my `/opt/boxen/env.d` directory

**Comment by jacebrowning** [comment]
If you manually delete `90_relative_bin_on_path.sh`, does it get recreated on the next `boxen` run?

**Comment by norm-modustri** [comment]
Yes, running boxes re-creates the script.

**Comment by jacebrowning** [comment]
In which file are you adding `/Users/normbarnard/bin` to your path? Maybe you want to insert your custom bin first?

**Comment by norm-modustri** [comment]
Yep, that's what I ended up doing.

**Comment by jacebrowning** [comment]
Did that fix the issue?

**Comment by norm-modustri** [comment]
Yes.

**Comment by jacebrowning** [comment]
In that case, I think it's functioning as expected and custom paths should always be placed first.
